spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "0.0.3"

accounts:
  message: "Welcome to PROD environment Loans Microservice"
  contactDetails:
    email: "production@test.com"
    name: "Production Team"

  onCallSupport:
    - "999-456-7890"
    - "999-765-4321"

